launch:
	@echo Checking port 8000...
	-@cmd /C "for /f \"tokens=5\" %%a in ('netstat -ano ^| findstr :8000 ^| findstr LISTENING') do taskkill /F /PID %%a"
	@echo Starting FastAPI...
	@uvicorn server:app --reload