"""test

Revision ID: 0b83af8e822e
Revises: a9b8c7d6e5f4
Create Date: 2026-02-24 19:12:58.373050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b83af8e822e'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_institution_id'), table_name='activities')
    op.drop_table('activities')
    op.add_column('assignments', sa.Column('max_score', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('classes', sa.Column('is_custom', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'is_custom')
    op.drop_column('assignments', 'max_score')
    op.create_table('activities',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('institution_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('entity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('performed_by', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('performer_role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('performer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_activities_institution_id'), 'activities', ['institution_id'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    # ### end Alembic commands ###
