# """added fee structure for installment payment

# Revision ID: 34457ceffd6d
# Revises: d4fe0ebb476c
# Create Date: 2026-04-09 14:56:28.005849

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import mysql

# # revision identifiers, used by Alembic.
# revision: str = '34457ceffd6d'
# down_revision: Union[str, Sequence[str], None] = 'd4fe0ebb476c'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
    
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('school_fees', schema=None) as batch_op:
#         batch_op.drop_index(batch_op.f('ix_school_fees_school_level'))

#     op.drop_table('school_fees')
#     with op.batch_alter_table('fee_installments', schema=None) as batch_op:
#         batch_op.drop_index(batch_op.f('ix_fee_installment_due_date'))
#         batch_op.drop_index(batch_op.f('ix_fee_installment_tenant'))
#         batch_op.drop_index(batch_op.f('ix_fee_installments_tenant_id'))

#     op.drop_table('fee_installments')
#     with op.batch_alter_table('schools', schema=None) as batch_op:
#         batch_op.drop_index(batch_op.f('ix_schools_institution_id'))

#     op.drop_table('schools')
#     with op.batch_alter_table('fee_structures', schema=None) as batch_op:
#         batch_op.drop_index(batch_op.f('ix_fee_structure_tenant'))
#         batch_op.drop_index(batch_op.f('ix_fee_structures_tenant_id'))

#     op.drop_table('fee_structures')
#     with op.batch_alter_table('branches', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True))
#         batch_op.add_column(sa.Column('fee_deadline', sa.DateTime(), nullable=True))

#     with op.batch_alter_table('system_settings', schema=None) as batch_op:
#         batch_op.alter_column('access_token_expire_minutes',
#                existing_type=mysql.INTEGER(display_width=11),
#                server_default=None,
#                existing_nullable=False)
#         batch_op.alter_column('refresh_token_expire_days',
#                existing_type=mysql.INTEGER(display_width=11),
#                server_default=None,
#                existing_nullable=False)

#     with op.batch_alter_table('tenants', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True))
#         batch_op.add_column(sa.Column('fee_deadline', sa.DateTime(), nullable=True))

#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('tenants', schema=None) as batch_op:
#         batch_op.drop_column('fee_deadline')
#         batch_op.drop_column('fee_amount')

#     with op.batch_alter_table('system_settings', schema=None) as batch_op:
#         batch_op.alter_column('refresh_token_expire_days',
#                existing_type=mysql.INTEGER(display_width=11),
#                server_default=sa.text('1'),
#                existing_nullable=False)
#         batch_op.alter_column('access_token_expire_minutes',
#                existing_type=mysql.INTEGER(display_width=11),
#                server_default=sa.text('60'),
#                existing_nullable=False)

#     with op.batch_alter_table('branches', schema=None) as batch_op:
#         batch_op.drop_column('fee_deadline')
#         batch_op.drop_column('fee_amount')

#     op.create_table('fee_structures',
#     sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
#     sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
#     sa.Column('fee_deadline', mysql.DATETIME(), nullable=True),
#     sa.Column('academic_year', mysql.VARCHAR(length=50), nullable=True),
#     sa.Column('created_at', mysql.DATETIME(), nullable=False),
#     sa.Column('updated_at', mysql.DATETIME(), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_default_charset='latin1',
#     mysql_engine='InnoDB'
#     )
#     with op.batch_alter_table('fee_structures', schema=None) as batch_op:
#         batch_op.create_index(batch_op.f('ix_fee_structures_tenant_id'), ['tenant_id'], unique=False)
#         batch_op.create_index(batch_op.f('ix_fee_structure_tenant'), ['tenant_id'], unique=False)

#     op.create_table('schools',
#     sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
#     sa.Column('institution_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
#     sa.Column('code', mysql.VARCHAR(length=64), nullable=True),
#     sa.Column('description', mysql.TEXT(), nullable=True),
#     sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
#     sa.Column('sort_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('created_at', mysql.DATETIME(), nullable=False),
#     sa.Column('updated_at', mysql.DATETIME(), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_default_charset='latin1',
#     mysql_engine='InnoDB'
#     )
#     with op.batch_alter_table('schools', schema=None) as batch_op:
#         batch_op.create_index(batch_op.f('ix_schools_institution_id'), ['institution_id'], unique=False)

#     op.create_table('fee_installments',
#     sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
#     sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
#     sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
#     sa.Column('due_date', mysql.DATETIME(), nullable=False),
#     sa.Column('order_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
#     sa.Column('is_active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('created_at', mysql.DATETIME(), nullable=False),
#     sa.Column('updated_at', mysql.DATETIME(), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_default_charset='latin1',
#     mysql_engine='InnoDB'
#     )
#     with op.batch_alter_table('fee_installments', schema=None) as batch_op:
#         batch_op.create_index(batch_op.f('ix_fee_installments_tenant_id'), ['tenant_id'], unique=False)
#         batch_op.create_index(batch_op.f('ix_fee_installment_tenant'), ['tenant_id'], unique=False)
#         batch_op.create_index(batch_op.f('ix_fee_installment_due_date'), ['due_date'], unique=False)

#     op.create_table('school_fees',
#     sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
#     sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('level', mysql.VARCHAR(length=20), nullable=False),
#     sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
#     sa.Column('fee_deadline', mysql.DATETIME(), nullable=True),
#     sa.Column('created_at', mysql.DATETIME(), nullable=False),
#     sa.Column('updated_at', mysql.DATETIME(), nullable=True),
#     sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('school_fees_ibfk_1'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_default_charset='latin1',
#     mysql_engine='InnoDB'
#     )
#     with op.batch_alter_table('school_fees', schema=None) as batch_op:
#         batch_op.create_index(batch_op.f('ix_school_fees_school_level'), ['school_id', 'level'], unique=True)

#     # ### end Alembic commands ###


"""added fee structure for installment payment

Revision ID: 34457ceffd6d
Revises: d4fe0ebb476c
Create Date: 2026-04-09 14:56:28.005849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34457ceffd6d'
down_revision: Union[str, Sequence[str], None] = 'd4fe0ebb476c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop tables that depend on others first (child tables)
    # Drop foreign key + index on school_fees before dropping the table
    with op.batch_alter_table('school_fees', schema=None) as batch_op:
        # Drop the foreign key constraint first (this is the key fix)
        batch_op.drop_constraint('school_fees_ibfk_1', type_='foreignkey')
        # Now safely drop the index
        batch_op.drop_index(batch_op.f('ix_school_fees_school_level'))

    # Drop the tables (order: children before parents)
    op.drop_table('school_fees')
    op.drop_table('fee_installments')
    op.drop_table('fee_structures')
    op.drop_table('schools')

    # 2. Now perform the structural changes (add columns)
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fee_deadline', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fee_deadline', sa.DateTime(), nullable=True))

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('access_token_expire_minutes',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('refresh_token_expire_days',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    # Revert column changes first
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('fee_deadline')
        batch_op.drop_column('fee_amount')

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('refresh_token_expire_days',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text('1'),
               existing_nullable=False)
        batch_op.alter_column('access_token_expire_minutes',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text('60'),
               existing_nullable=False)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('fee_deadline')
        batch_op.drop_column('fee_amount')

    # Recreate the dropped tables (in reverse order: parents before children)
    op.create_table('schools',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('institution_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
        sa.Column('code', mysql.VARCHAR(length=64), nullable=True),
        sa.Column('description', mysql.TEXT(), nullable=True),
        sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('sort_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='latin1',
        mysql_engine='InnoDB'
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_institution_id'), ['institution_id'], unique=False)

    op.create_table('fee_structures',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('fee_deadline', mysql.DATETIME(), nullable=True),
        sa.Column('academic_year', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='latin1',
        mysql_engine='InnoDB'
    )
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structures_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structure_tenant'), ['tenant_id'], unique=False)

    op.create_table('fee_installments',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('due_date', mysql.DATETIME(), nullable=False),
        sa.Column('order_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
        sa.Column('is_active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='latin1',
        mysql_engine='InnoDB'
    )
    with op.batch_alter_table('fee_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_installments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_installment_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_installment_due_date'), ['due_date'], unique=False)

    op.create_table('school_fees',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('level', mysql.VARCHAR(length=20), nullable=False),
        sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('fee_deadline', mysql.DATETIME(), nullable=True),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('school_fees_ibfk_1'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='latin1',
        mysql_engine='InnoDB'
    )
    with op.batch_alter_table('school_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_fees_school_level'), ['school_id', 'level'], unique=True)

    # ### end Alembic commands ###