"""added dismissal table

Revision ID: 7edf0a51b08d
Revises: 
Create Date: 2026-03-09 19:48:28.752402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edf0a51b08d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reminder_dismissals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reminder_id', sa.Integer(), nullable=False),
        sa.Column('dismissed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['reminder_id'], ['schedule_reminders.id'], name=op.f('user_reminder_dismissals_ibfk_1')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_reminder_dismissals_ibfk_2')),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_reminder_dismissals', schema=None) as batch_op:
        batch_op.create_index('ix_user_reminder_dismissal_unique', ['user_id', 'reminder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reminder_dismissals', schema=None) as batch_op:
        batch_op.drop_index('ix_user_reminder_dismissal_unique')

    op.drop_table('user_reminder_dismissals')
    # ### end Alembic commands ###
