"""add_fields_to_tenant_model

Revision ID: 87ff93055548
Revises: 8de29cb9ac1c
Create Date: 2026-02-23 14:52:52.771450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ff93055548'
down_revision: Union[str, Sequence[str], None] = '8de29cb9ac1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add domain column
    op.add_column('tenants', sa.Column('domain', sa.String(length=200), nullable=True))
    
    # Add is_active column with default
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    
    # Add created_at with default
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    
    # Add updated_at
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Set updated_at for existing rows
    op.execute("UPDATE tenants SET updated_at = COALESCE(created_at, NOW()) WHERE updated_at IS NULL")
    
    # Create unique constraint on name
    op.create_unique_constraint('uq_tenants_name', 'tenants', ['name'])
    
    # Remove server defaults after setting values
    op.alter_column('tenants', 'is_active', 
                    existing_type=sa.Boolean(), 
                    server_default=None)
    op.alter_column('tenants', 'created_at', 
                    existing_type=sa.DateTime(), 
                    server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenants_name', 'tenants', type_='unique')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'domain')
    # ### end Alembic commands ###
