"""add_user_type_to_user

Revision ID: 8e74aa2196f1
Revises: 7dd14c59ef7b
Create Date: 2026-02-23 13:56:06.547323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e74aa2196f1'
down_revision: Union[str, Sequence[str], None] = '7dd14c59ef7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value
    op.add_column('users', sa.Column('user_type', sa.String(length=20), nullable=False, server_default='TENANT'))
    # Update existing users: if role starts with 'system_', set user_type to 'SYSTEM', otherwise 'TENANT'
    op.execute("""
        UPDATE users 
        SET user_type = CASE 
            WHEN role LIKE 'system_%' THEN 'SYSTEM' 
            ELSE 'TENANT' 
        END
    """)
    # Remove server default after setting values
    op.alter_column('users', 'user_type', server_default=None)
    # Make institution_id nullable for system users (MySQL requires existing type)
    op.alter_column('users', 'institution_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert institution_id to not nullable (set default for NULL values first)
    op.execute("UPDATE users SET institution_id = 0 WHERE institution_id IS NULL")
    op.alter_column('users', 'institution_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
