"""added addeddeleted_at field in the schools  table

Revision ID: cfaf85fd0603
Revises: b5f5287933f6
Create Date: 2026-04-12 22:48:34.709328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfaf85fd0603'
down_revision: Union[str, Sequence[str], None] = 'b5f5287933f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structure_tenant'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_tenant_id'))

    op.drop_table('fee_structures')
    with op.batch_alter_table('school_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_fees_school_level'))

    op.drop_table('school_fees')
    with op.batch_alter_table('student_payment_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_payment_installments_institution_id'))
        batch_op.drop_index(batch_op.f('ix_student_payment_installments_school_id'))
        batch_op.drop_index(batch_op.f('ix_student_payment_installments_student'))
        batch_op.drop_index(batch_op.f('ix_student_payment_installments_student_id'))

    op.drop_table('student_payment_installments')
    with op.batch_alter_table('fee_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_installment_due_date'))
        batch_op.drop_index(batch_op.f('ix_fee_installment_school'))
        batch_op.drop_index(batch_op.f('ix_fee_installment_school_level'))
        batch_op.drop_index(batch_op.f('ix_fee_installment_tenant'))
        batch_op.drop_index(batch_op.f('ix_fee_installments_school_id'))
        batch_op.drop_index(batch_op.f('ix_fee_installments_tenant_id'))

    op.drop_table('fee_installments')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_institution_id'))

    op.drop_table('schools')
    with op.batch_alter_table('student_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_payments_institution_id'))
        batch_op.drop_index(batch_op.f('ix_student_payments_school_id'))
        batch_op.drop_index(batch_op.f('ix_student_payments_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_payments_student_school_level'))

    op.drop_table('student_payments')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    op.create_table('student_payments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('institution_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('level', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('is_fully_paid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_paid', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('academic_year', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_payment_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('student_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_payments_student_school_level'), ['student_id', 'school_id', 'level'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_payments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_payments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_payments_institution_id'), ['institution_id'], unique=False)

    op.create_table('schools',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('institution_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_institution_id'), ['institution_id'], unique=False)

    op.create_table('fee_installments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('level', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('due_date', mysql.DATETIME(), nullable=False),
    sa.Column('order_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_due', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_overdue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('fee_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_installments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_installments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_installment_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_installment_school_level'), ['school_id', 'level'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_installment_school'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_installment_due_date'), ['due_date'], unique=False)

    op.create_table('student_payment_installments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('institution_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('installment_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('required_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('due_date', mysql.DATETIME(), nullable=False),
    sa.Column('is_paid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('payment_date', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_payment_id'], ['student_payments.id'], name=op.f('student_payment_installments_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('student_payment_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_payment_installments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_payment_installments_student'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_payment_installments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_payment_installments_institution_id'), ['institution_id'], unique=False)

    op.create_table('school_fees',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('level', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fee_deadline', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('school_fees_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('school_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_fees_school_level'), ['school_id', 'level'], unique=True)

    op.create_table('fee_structures',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fee_deadline', mysql.DATETIME(), nullable=True),
    sa.Column('academic_year', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structures_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structure_tenant'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###
