"""added fee structure for installment payment

Revision ID: f11502e0e519
Revises: 34457ceffd6d
Create Date: 2026-04-09 15:05:26.642692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f11502e0e519'
down_revision: Union[str, Sequence[str], None] = '34457ceffd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_installment_due_date'))
        batch_op.drop_index(batch_op.f('ix_fee_installment_tenant'))
        batch_op.drop_index(batch_op.f('ix_fee_installments_tenant_id'))

    op.drop_table('fee_installments')
    with op.batch_alter_table('school_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_fees_school_level'))

    op.drop_table('school_fees')
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structure_tenant'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_tenant_id'))

    op.drop_table('fee_structures')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_institution_id'))

    op.drop_table('schools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('institution_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_institution_id'), ['institution_id'], unique=False)

    op.create_table('fee_structures',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fee_deadline', mysql.DATETIME(), nullable=True),
    sa.Column('academic_year', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structures_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structure_tenant'), ['tenant_id'], unique=False)

    op.create_table('school_fees',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('level', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fee_deadline', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('school_fees_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('school_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_fees_school_level'), ['school_id', 'level'], unique=True)

    op.create_table('fee_installments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('due_date', mysql.DATETIME(), nullable=False),
    sa.Column('order_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('fee_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_installments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_installment_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_installment_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###
